adjective = [
    "abandoned", "able", "absolute", "academic", "acceptable", "acclaimed", "accomplished", "accurate", "aching", "acidic", "acrobatic",
     "active", "actual", "adept", "admirable", "admired", "adolescent", "adorable", "adored", "advanced", "adventurous", "affectionate", "afraid",
     "aged", "aggravating", "aggressive", "agile", "agitated", "agonizing", "agreeable", "ajar", "alarmed", "alarming", "alert", "alienated",
     "alive", "all", "altruistic", "amazing", "ambitious", "ample", "amused", "amusing", "anchored", "ancient", "angelic", "angry", "anguished",
     "animated", "annual", "another", "antique", "anxious", "any", "apprehensive", "appropriate", "apt", "arctic", "arid", "arrogant", "artistic",
     "ashamed", "aspiring", "athletic", "attached", "attentive", "attractive", "audacious", "audible", "aural", "austere", "authentic",
     "authorized", "automatic", "avaricious", "average", "aware", "awesome", "awful", "awkward", "babyish", "back", "bad", "baggy", "bare",
     "barren", "basic", "beautiful", "belated", "beloved", "beneficial", "best", "better", "bewitched", "big", "big-hearted", "biodegradable",
     "bite-sized", "bitter", "black", "black-and-white", "bland", "blank", "blaring", "bleak", "blind", "blissful", "blond", "blue", "blushing",
     "bogus", "boiling", "bold", "bony", "boring", "bossy", "both", "bouncy", "bountiful", "bowed", "brave", "breakable", "brief", "bright",
     "brilliant", "brisk", "broken", "bronze", "brown", "bruised", "bubbly", "bulky", "bumpy", "buoyant", "burdensome", "burly", "bustling",
     "busy", "buttery", "buzzing", "calculating", "calm", "candid", "canine", "capital", "carefree", "careful", "careless", "caring", "cautious",
     "cavernous", "celebrated", "charming", "cheap", "cheerful", "cheery", "chief", "chilly", "chubby", "circular", "classic", "clean", "clear",
     "clear-cut", "clever", "close", "closed", "cloudy", "clueless", "clumsy", "cluttered", "coarse", "cold", "colorful", "colorless", "colossal",
     "comfortable", "common", "compassionate", "competent", "complete", "complex", "complicated", "composed", "concerned", "concrete", "confused",
     "conscious", "considerate", "constant", "content", "conventional", "cooked", "cool", "cooperative", "coordinated", "corny", "corrupt",
     "costly", "courageous", "courteous", "crafty", "crazy", "creamy", "creative", "creepy", "criminal", "crisp", "critical", "crooked",
     "crowded", "cruel", "crushing", "cuddly", "cultivated", "cultured", "cumbersome", "curly", "curvy", "cute", "cylindrical", "damaged", "damp",
     "dangerous", "dapper", "daring", "dark", "darling", "dazzling", "dead", "deadly", "deafening", "dear", "dearest", "decent", "decimal",
     "decisive", "decrepit", "deep", "defenseless", "defensive", "defiant", "deficient", "definite", "definitive", "deft", "delayed",
     "delectable", "delicious", "delightful", "delirious", "demanding", "demonic", "dense", "dental", "dependable", "dependent", "derelict",
     "descriptive", "deserted", "desolate", "detailed", "determined", "devoted", "different", "difficult", "digital", "diligent", "dim",
     "dimpled", "dimwitted", "direct", "disastrous", "discrete", "disfigured", "disgusting", "disloyal", "dismal", "distant", "distinct",
     "distorted", "dizzy", "dopey", "doting", "double", "downright", "drab", "drafty", "dramatic", "dreary", "droopy", "dry", "dual", "dull",
     "dutiful", "each", "eager", "early", "earnest", "easy", "easy-going", "ecstatic", "edible", "educated", "elaborate", "elastic", "elated",
     "elderly", "electric", "elegant", "elementary", "elite", "elliptical", "eloquent", "elusive", "embarrassed", "embellished", "eminent",
     "emotional", "empty", "enchanted", "enchanting", "energetic", "enlightened", "enormous", "enraged", "entire", "envious", "equal",
     "equatorial", "essential", "esteemed", "ethical", "euphoric", "even", "evergreen", "everlasting", "every", "evil", "exalted", "excellent",
     "excitable", "excited", "exciting", "exemplary", "exhausted", "expectant", "expensive", "experienced", "expert", "extra-large",
     "extra-small", "extraneous", "extroverted", "fabulous", "failing", "faint", "fair", "faithful", "fake", "false", "familiar", "famous",
     "fancy", "fantastic", "far", "faraway", "fast", "fat", "fatal", "fatherly", "favorable", "favorite", "fearful", "fearless", "feeble",
     "feisty", "felicitous", "feline", "felt", "female", "feminine", "feral", "ferocious", "fetid", "few", "fickle", "fierce", "figurative",
     "filthy", "final", "fine", "finished", "firm", "first", "firsthand", "fit", "fitting", "fixed", "flaky", "flamboyant", "flashy", "flat",
     "flawed", "flawless", "flickering", "flimsy", "flippant", "flowery", "fluffy", "fluid", "flustered", "focused", "foggy", "fond", "foolhardy",
     "foolish", "forbidden", "forced", "forceful", "forged", "forked", "formal", "forsaken", "forthright", "fortunate", "fragile", "fragrant",
     "frail", "frank", "fraught", "frayed", "freaky", "free", "french", "frequent", "fresh", "friendly", "frightened", "frightening", "frigid",
     "frilly", "frivolous", "frizzy", "front", "frosty", "frozen", "frugal", "fruitful", "frumpy", "full", "fumbling", "functional", "funny",
     "fussy", "fuzzy", "gargantuan", "gaseous", "general", "generous", "gentle", "genuine", "giant", "giddy", "gifted", "gigantic", "giving",
     "glamorous", "glaring", "glass", "gleaming", "gleeful", "glistening", "glittering", "gloomy", "glorious", "glossy", "glum", "golden", "good",
     "good-natured", "gorgeous", "graceful", "gracious", "grand", "grandiose", "granular", "grateful", "grave", "gray", "great", "greedy",
     "green", "gregarious", "grim", "grimy", "gripping", "grizzled", "gross", "grotesque", "grouchy", "grounded", "growing", "growling", "grown",
     "grubby", "gruesome", "grumpy", "guilty", "gullible", "gummy", "hairy", "half", "handmade", "handsome", "handy", "happy", "hard", "harmful",
     "harmless", "harmonious", "harsh", "hasty", "hateful", "haunting", "healthy", "heartfelt", "hearty", "heavenly", "heavy", "hefty", "helpful",
     "helpless", "hidden", "hideous", "high", "high-level", "hilarious", "hoarse", "hollow", "homely", "honest", "honorable", "honored",
     "hopeful", "horrible", "hospitable", "hot", "huge", "humble", "humiliating", "humming", "humongous", "hungry", "hurtful", "husky",
     "hygienic", "hypnotic", "hysterical", "icy", "ideal", "idealistic", "identical", "idiotic", "idle", "idolized", "ignorant", "ill",
     "ill-fated", "ill-informed", "illegal", "illegible", "illiterate", "illustrious", "imaginary", "imaginative", "immaculate", "immaterial",
     "immature", "immediate", "immense", "impartial", "impassioned", "impeccable", "imperfect", "impertinent", "imperturbable", "impish",
     "impolite", "important", "impossible", "impractical", "impressionable", "impressive", "inaccurate", "inactive", "inadequate",
     "inappropriate", "incandescent", "incompetent", "incomplete", "incredible", "indifferent", "indigo", "indolent", "ineffective",
     "inefficient", "inexpensive", "infinite", "infinitesimal", "inflexible", "innocent", "inquisitive", "insane", "insidious", "insignificant",
     "insincere", "intelligent", "intense", "intentional", "interesting", "internal", "intrepid", "intriguing", "invincible", "invisible",
     "irate", "iridescent", "irksome", "ironic", "irrational", "irresponsible", "irritable", "jaded", "jagged", "jailed", "jam-packed", "jangly",
     "jarring", "jaundiced", "jaunty", "jealous", "jittery", "jobless", "jovial", "joyful", "joyous", "jubilant", "judicious", "juicy", "jumbled",
     "jumbo", "jumpy", "junior", "junky", "juvenile", "keen", "kind", "kindhearted", "knavish", "knotty", "knowing", "knowledgeable",
     "lackadaisical", "lame", "languid", "large", "late", "laughable", "lavish", "lazy", "lean", "legal", "legible", "legitimate", "lengthy",
     "lethal", "level", "lively", "livid", "lonely", "loose", "lopsided", "loud", "lovable", "lovely", "loving", "low", "loyal", "lucky",
     "ludicrous", "luminous", "lustrous", "luxurious", "macabre", "magenta", "magnificent", "majestic", "malevolent", "malicious", "mammoth",
     "manageable", "mandatory", "massive", "mature", "mauve", "meager", "mealy", "mean", "measly", "meaty", "mediocre", "melancholy", "mellow",
     "melodic", "melted", "menacing", "merciful", "mere", "merry", "messy", "mighty", "mild", "militant", "mindless", "miniature", "minor",
     "miserable", "miserly", "misguided", "misty", "mixed", "modern", "modest", "moise", "moist", "molecular", "monstrous", "monumental",
     "morbid", "moribund", "moronic", "mournful", "mundane", "murky", "mushy", "musty", "mute", "mysterious", "naive", "narrow", "nasty",
     "natural", "naughty", "neat", "nebulous", "necessary", "needless", "needy", "negative", "neglected", "negligent", "nervous", "new", "nice",
     "nickel-plated", "nifty", "nimble", "noisy", "nomadic", "nondescript", "nonstop", "normal", "norse", "nostalgic", "nosy", "noteworthy",
     "noxious", "null", "numb", "obedient", "obese", "oblivious", "obnoxious", "obscene", "obscure", "observant", "obsolete", "obstinate",
     "occasional", "ochre", "odd", "offbeat", "old", "old-fashioned", "ominous", "onset", "open", "opposite", "optimal", "orange", "orderly",
     "ordinary", "organic", "original", "ornate", "ornery", "ossified", "overt", "overwrought", "painful", "pale", "paltry", "panicky",
     "parsimonious", "past", "perfect", "petite", "petty", "phobic", "pink", "placid", "plain", "plausible", "pleasant", "plucky", "polite",
     "poor", "popular", "positive", "possible", "potent", "powerful", "precious", "premium", "pretty", "previous", "pricey", "prickly", "private",
     "probable", "productive", "profuse", "proper", "protective", "proud", "psychedelic", "psychotic", "public", "puffy", "pungent", "puny",
     "pure", "purple", "quaint", "quarrelsome", "quick", "quickest", "quiet", "quirky", "quixotic", "rabid", "racial", "ragged", "rampant",
     "rapid", "rare", "raspy", "ratty", "raw", "rebel", "receptive", "redundant", "reflective", "regular", "relieved", "repugnant", "resilient",
     "resonant", "responsible", "right", "righteous", "rigid", "ripe", "ritzy", "robust", "romantic", "roomy", "rotten", "rough", "round",
     "ruddy", "rude", "rural", "rustic", "ruthless", "sable", "sacred", "sad", "safe", "saline", "salty", "same", "sapphire", "sappy", "sassy",
     "satisfying", "scared", "scary", "scattered", "scientific", "scintillating", "scrawny", "screeching", "second", "secret", "secure", "sedate",
     "seemingly", "seemly", "seething", "selfish", "selfless", "seminal", "sensitive", "serene", "serious", "sexy", "sharp", "shiny", "short",
     "showy", "shy", "sick", "silent", "silky", "silly", "simple", "sincere", "single", "singular", "skillful", "skinny", "sleek", "sleepy",
     "slim", "slimy", "slippery", "sloppy", "slow", "small", "smart", "smelly", "smiling", "smooth", "sneaky", "snobbish", "soft", "soggy",
     "sole", "solid", "somber", "sophisticated", "sordid", "sore", "sour", "sparkling", "special", "spectacular", "spicy", "spiffy", "spiky",
     "spiritual", "spiteful", "splendid", "spooky", "spotless", "spotty", "square", "squealing", "squeamish", "stale", "steady", "steep",
     "stereotyped", "sticky", "stiff", "stimulating", "stingy", "stormy", "straight", "strange", "striped", "strong", "stupendous", "stupid",
     "sturdy", "subdued", "subsequent", "substantial", "successful", "succinct", "sudden", "sulky", "super", "superb", "superficial", "supple",
     "supreme", "swanky", "sweet", "swell", "swift", "symptomatic", "synonymous", "taboo", "tacit", "tacky", "talented", "tall", "tame", "tan",
     "tangible", "tangy", "tart", "tasteful", "tasty", "tawdry", "team-oriented", "tearful", "tedious", "teeny", "telling", "temporary", "ten",
     "tenacious", "tender", "tense", "tenuous", "terrible", "terrific", "terse", "tested", "testy", "thankful", "thankless", "therapeutic",
     "thick", "thin", "thinkable", "third", "thirsty", "thorough", "thoughtful", "thoughtless", "threatening", "thundering", "tidy", "tight",
     "timely", "tiny", "tired", "tiresome", "toothsome", "torpid", "tough", "towering", "tranquil", "trashy", "tremendous", "tricky", "trite",
     "troubled", "truculent", "true", "truthful", "turn-key", "tweed", "typical", "ubiquitous", "ugliest", "ugly", "ultra", "unable",
     "unaccountable", "unadvised", "unarmed", "unbecoming", "unbiased", "uncovered", "understood", "undesirable", "unequal", "unequaled",
     "uneven", "unhealthy", "uninterested", "unique", "unkempt", "unknown", "unnatural", "unruly", "unsightly", "unsuitable", "untidy", "unused",
     "unusual", "unwieldy", "unwritten", "upbeat", "uppity", "upset", "uptight", "useful", "useless", "utopian", "utter", "uttermost", "vacuous",
     "vagabond", "vague", "valuable", "various", "vast", "vengeful", "venomous", "verdant", "versed", "victorious", "vigorous", "violent",
     "violet", "vivacious", "vivid", "voiceless", "volatile", "voracious", "vulgar", "wacky", "waggish", "waiting", "wakeful", "wandering",
     "warm", "wary", "wasteful", "watery", "weak", "wealthy", "weary", "wee", "weeping", "weepy", "weighty", "welsh", "wet", "whimsical",
     "whispering"
     ]