adverb = [
    "abnormally", "abruptly", "absently", "absolutely", "abundantly", "accidentally", "accurately", "acidly", "actually", "acutely", "adamantly",
     "adequately", "admirably", "adoringly", "adversely", "affectingly", "affectionately", "affirmatively", "afterward", "again", "agreeably",
     "aimlessly", "almost", "already", "always", "amazingly", "angrily", "annoyingly", "annually", "anxiously", "anyhow", "anyway", "anywhere",
     "appallingly", "apparently", "appreciably", "appropriately", "around", "arrogantly", "artistically", "ashamedly", "aside", "assuredly",
     "astonishingly", "astray", "astutely", "attentively", "attractively", "audibly", "austerely", "authoritatively", "automatically",
     "awkwardly", "badly", "barely", "basically", "beautifully", "before", "begrudgingly", "believably", "belligerently", "below", "beneficially",
     "best", "better", "bewilderingly", "bitterly", "bizarrely", "blatantly", "blindly", "blissfully", "boldly", "boringly", "both", "bravely",
     "briefly", "brightly", "briskly", "broadly", "busily", "calmly", "candidly", "carefully", "carelessly", "casually", "cautiously",
     "certainly", "charmingly", "cheerfully", "clearly", "cleverly", "closely", "coherently", "coldly", "colorfully", "commonly", "completely",
     "consequently", "conservatively", "considerably", "consistently", "constantly", "constructively", "continually", "continuously",
     "conveniently", "correctly", "courageously", "covertly", "crazily", "curiously", "currently", "cynically", "daily", "daintily",
     "dangerously", "daringly", "darkly", "dearly", "decently", "deeply", "defiantly", "definitely", "deliberately", "delicately", "desperately",
     "determinedly", "differently", "directly", "disastrously", "discreetly", "distinctly", "divisively", "doubtfully", "down", "dramatically",
     "dully", "eagerly", "early", "easily", "economically", "effectively", "efficiently", "effortlessly", "elaborately", "elegantly", "elsewhere",
     "emotionally", "emphatically", "endlessly", "energetically", "enormously", "enough", "enthusiastically", "entirely", "equally", "especially",
     "essentially", "eternally", "ethically", "even", "evenly", "eventually", "ever", "everywhere", "evidently", "exactly", "excessively",
     "excitedly", "exclusively", "expectedly", "expertly", "explicitly", "externally", "extremely", "fairly", "faithfully", "famously", "far",
     "fast", "fatally", "favorably", "fearfully", "fervently", "fiercely", "finally", "financially", "firmly", "fluently", "fondly", "foolishly",
     "forever", "formally", "formerly", "fortunately", "frankly", "freely", "frequently", "fully", "furiously", "generally", "generously",
     "gently", "genuinely", "gladly", "glibly", "gracefully", "gratefully", "greatly", "grievously", "grudgingly", "habitually", "half",
     "happily", "hard", "hardly", "harshly", "hastily", "healthily", "heartily", "heavily", "helpfully", "hence", "highly", "honestly",
     "hopefully", "hopelessly", "horribly", "hourly", "however", "humbly", "hungrily", "immediately", "impatiently", "impressively",
     "inadvertently", "inappropriately", "incredibly", "indeed", "independently", "indirectly", "inevitably", "infrequently", "innocently",
     "inquisitively", "instantly", "intelligently", "intensely", "intentionally", "intently", "interestingly", "inwardly", "ironically",
     "irritably", "jokingly", "jovially", "joyfully", "joyously", "judiciously", "just", "justly", "keenly", "kiddingly", "kindly", "knowingly",
     "lastly", "late", "lately", "later", "lazily", "least", "less", "lightly", "likely", "literally", "loudly", "lovingly", "loyally", "luckily",
     "madly", "mainly", "majorly", "manually", "markedly", "materially", "meanwhile", "merely", "merrily", "methodically", "mightily", "mildly",
     "minutely", "miserably", "mockingly", "modestly", "monthly", "mostly", "mysteriously", "naturally", "nearly", "neatly", "necessarily",
     "never", "nevertheless", "next", "nicely", "noisily", "normally", "notably", "noticeably", "now", "nowhere", "obediently", "obligingly",
     "obviously", "occasionally", "oddly", "offensively", "officially", "often", "only", "openly", "optimistically", "orderly", "ordinarily",
     "out", "outdoors", "overly", "painfully", "partially", "particularly", "passionately", "patiently", "perfectly", "persistently",
     "personally", "physically", "plainly", "pleasantly", "please", "politely", "poorly", "positively", "possibly", "potentially", "precisely",
     "predominantly", "presently", "presumably", "previously", "primarily", "probably", "promptly", "properly", "proudly", "publicly", "purely",
     "quickly", "quietly", "quite", "randomly", "rapidly", "rarely", "readily", "really", "reasonably", "recently", "regularly", "reluctantly",
     "repeatedly", "reportedly", "respectably", "respectfully", "restfully", "richly", "right", "righteously", "rightly", "rigidly", "roughly",
     "rudely", "sadly", "safely", "sarcastically", "scarcely", "scarily", "scientifically", "secretly", "securely", "sedately", "seemingly",
     "seldom", "selfishly", "separately", "seriously", "shamelessly", "sharply", "shortly", "shrilly", "shyly", "significantly", "silently",
     "similarly", "simply", "sincerely", "skillfully", "slowly", "smoothly", "softly", "solely", "solemnly", "solidly", "sometimes", "somewhat",
     "somewhere", "soon", "specifically", "speedily", "spiritually", "splendidly", "sporadically", "startlingly", "steadily", "still", "strictly",
     "strongly", "stubbornly", "stunningly", "subsequently", "substantially", "successfully", "suddenly", "sufficiently", "suitably", "surely",
     "surprisingly", "suspiciously", "swiftly", "sympathetically", "systematically", "tactfully", "temporarily", "tenderly", "tensely",
     "thankfully", "then", "there", "therefore", "thoroughly", "thoughtfully", "thus", "tightly", "timely", "today", "together", "tomorrow",
     "too", "totally", "touchingly", "traditionally", "truly", "truthfully", "typically", "ultimately", "unbelievably", "unconditionally",
     "understandably", "unfortunately", "uniformly", "unilaterally", "uniquely", "unnaturally", "unnecessarily", "unquestionably", "unusually",
     "up", "upstairs", "usefully", "usually", "utterly", "vaguely", "vainly", "valiantly", "vastly", "verbally", "very", "viciously",
     "vigorously", "violently", "visibly", "vividly", "voluntarily", "warmly", "weakly", "wearily", "weekly", "weirdly", "well", "wetly",
     "wholly", "widely", "wildly", "willingly", "wisely", "wistfully", "wonderfully", "worriedly", "wrongly", "yearly", "yearningly", "yesterday",
     "yet", "zealously"]
