noun = [
    "accordion", "actor", "adventure", "airplane", "algae", "amethyst", "amphibian", "animal", "ant", "antenna", "aphid", "aphrodite", "appeal",
     "apple", "appliance", "apricot", "artichoke", "artist", "asteroid", "athlete", "audit", "author", "ball", "balloon", "bamboo", "barracuda",
     "battery", "bear", "beehive", "beet", "beetle", "bicycle", "bird", "blueberry", "book", "bridge", "bus", "butterfly", "cactus", "calculator",
     "candle", "canyon", "car", "carnival", "carrot", "cat", "cathedral", "celery", "chair", "child", "city", "clock", "cloud", "coat",
     "computer", "continent", "country", "creation", "crocodile", "cucumber", "daffodil", "daisy", "date", "deal", "debris", "debut", "debutante",
     "demeanor", "desk", "diamond", "dinosaur", "dog", "dolphin", "donut", "door", "drum", "dune", "dwarf", "eagle", "easel", "echo", "eel",
     "egg", "elephant", "engine", "enzyme", "eucalyptus", "eyebrow", "eyelash", "feather", "feline", "felon", "felt", "fern", "fig", "fight",
     "fighter", "filament", "fire", "firefly", "firelight", "fireplace", "firework", "fish", "fitness", "flamingo", "flower", "flute", "fog",
     "force", "forest", "fountain", "fox", "frame", "frank", "freight", "frenemy", "fries", "frog", "fruit", "fry", "fungus", "galaxy", "garden",
     "gazelle", "germ", "geyser", "giraffe", "glacier", "glimpse", "globe", "glove", "glow", "goal", "goat", "goblin", "goddess", "gold", "golf",
     "goose", "gorilla", "gospel", "gossip", "gourmet", "grace", "grape", "grapefruit", "grass", "gravity", "guitar", "gum", "guru", "habit",
     "hail", "haircut", "half", "hallway", "ham", "hamburger", "hammer", "happiness", "harbor", "harp", "harvest", "hat", "hatred", "he",
     "health", "hedgehog", "helicopter", "helix", "helmet", "her", "herb", "hero", "hers", "highlight", "hill", "him", "hint", "his", "hockey",
     "homework", "honey", "honeydew", "horror", "horse", "hospitality", "host", "human", "humidity", "hunger", "hunt", "hurdle", "hurricane",
     "hurry", "hyena", "ice", "iceberg", "icicle", "icon", "idea", "idiom", "ignorance", "iguana", "illusion", "image", "impact", "impala",
     "improvement", "incentive", "income", "independence", "indicator", "individual", "industry", "inequality", "infinity", "inflation",
     "information", "initiative", "injury", "injustice", "ink", "inquiry", "insect", "insight", "insult", "insurance", "integrity", "intensity",
     "intention", "interaction", "interest", "interference", "internet", "interview", "introduction", "invention", "investment", "iris", "iron",
     "irony", "island", "isotope", "it", "item", "its", "ivory", "jackal", "jacket", "jackfruit", "jaguar", "jalapeno", "jam", "jar", "javelin",
     "jazz", "jealousy", "jellybean", "jellyfish", "jewel", "jigsaw", "job", "joke", "journal", "journey", "joy", "judge", "jug", "juice", "jump",
     "jungle", "justice", "kale", "kaleidoscope", "kangaroo", "keen", "key", "keyboard", "kindness", "kingdom", "kingfisher", "kiss", "kite",
     "kitten", "kiwi", "knowledge", "koala", "kryptonite", "kumquat", "lab", "labor", "ladder", "lagoon", "lake", "lamb", "lamp", "landscape",
     "language", "laptop", "laugh", "laughter", "lawyer", "leader", "leadership", "league", "learning", "legacy", "legal", "legend", "lemon",
     "lemur", "leopard", "lesson", "letter", "liberty", "library", "license", "lifestyle", "lighthouse", "lightning", "likelihood", "lilac",
     "lily", "limit", "link", "lion", "liquid", "literacy", "literature", "llama", "lobby", "location", "logic", "loneliness", "longevity",
     "loss", "lottery", "love", "loyalty", "luck", "luggage", "luxury", "machine", "madness", "magazine", "magic", "magnet", "magnitude",
     "mailbox", "mainstream", "majority", "makeup", "mall", "mammal", "management", "mango", "manner", "manuscript", "map", "marathon", "march",
     "margarine", "margin", "marker", "market", "maturity", "maze", "me", "meal", "meaning", "mechanism", "medicine", "medium", "meerkat", "meme",
     "memory", "menu", "mercy", "merit", "mermaid", "message", "metal", "method", "microscope", "mile", "milk", "millennium", "mindset", "mine",
     "mineral", "minimum", "minnow", "miracle", "mischief", "misery", "mission", "mistake", "mix", "model", "molecule", "momentum", "money",
     "mongoose", "monopoly", "mood", "moon", "moose", "morality", "mortgage", "moss", "mountain", "mouse", "mug", "mushroom", "my", "mystery",
     "myth", "nachos", "nail", "narrative", "narwhal", "nation", "nature", "nebula", "necessity", "nectar", "nectarine", "net", "network",
     "neutron", "news", "night", "nightmare", "nobility", "node", "nomad", "nonsense", "noodle", "normal", "nose", "nostril", "notebook",
     "nothing", "novel", "novice", "nuance", "nucleus", "oasis", "obelisk", "obstacle", "occasion", "ocean", "octagon", "octopus", "offense",
     "oil", "onion", "opinion", "opportunity", "opposition", "option", "orange", "order", "origin", "ostrich", "otter", "our", "ours", "outcome",
     "outline", "outlook", "output", "owl", "oxygen", "oyster", "pace", "pain", "painting", "palace", "palm", "panel", "panic", "pant", "papaya",
     "paper", "parachute", "paradigm", "paragraph", "parallel", "parameter", "parent", "park", "parrot", "participation", "passage", "passion",
     "patent", "path", "patience", "pattern", "payment", "peace", "peach", "peak", "pear", "pen", "penalty", "pencil", "penguin", "pension",
     "people", "pepper", "percentage", "perception", "performance", "period", "permission", "personality", "perspective", "pet", "phenomenon",
     "philosophy", "phone", "photo", "physics", "piano", "picture", "piece", "pineapple", "place", "plane", "planet", "planning", "plate",
     "platform", "platypus", "play", "pleasure", "plot", "plum", "pocket", "poem", "poet", "point", "policy", "politics", "poll", "pollution",
     "population", "portfolio", "position", "possibility", "posture", "potato", "potential", "practice", "preference", "preparation", "presence",
     "pressure", "prestige", "price", "pride", "principle", "priority", "privacy", "probability", "procedure", "process", "product", "profile",
     "profit", "progress", "project", "promise", "prospect", "protocol", "provider", "province", "psychology", "publicity", "pulse", "purpose",
     "quail", "quality", "quantity", "quark", "quarter", "quartz", "quasar", "queen", "question", "queue", "quicksand", "quill", "quilt",
     "quince", "quinoa", "quokka", "quote", "raccoon", "race", "racoon", "radiation", "radish", "rain", "rainbow", "raspberry", "ratio",
     "rational", "rattlesnake", "reality", "reason", "recession", "recipe", "recognition", "record", "recruitment", "rectangle", "referral",
     "reflection", "reform", "regime", "region", "regulation", "relevance", "relief", "religion", "reptile", "reputation", "requirement",
     "research", "residence", "resistance", "resolution", "resource", "respect", "response", "responsibility", "rest", "result", "retail",
     "retirement", "return", "revenue", "review", "revolution", "rhombus", "rhythm", "rice", "rich", "ride", "right", "risk", "river", "road",
     "rocket", "role", "room", "rose", "routine", "rule", "safety", "salad", "salamander", "salami", "salary", "salt", "saltine", "sample",
     "sanction", "satellite", "satisfaction", "scale", "scarecrow", "scenario", "scene", "schedule", "scheme", "science", "scissors", "scope",
     "score", "scorpion", "screen", "script", "search", "season", "seat", "second", "secret", "section", "sector", "security", "segment",
     "selection", "self", "seller", "senior", "sense", "sentence", "sequence", "series", "serpent", "service", "session", "set", "setting",
     "share", "she", "sheep", "shelf", "ship", "shirt", "shock", "shoe", "shop", "short", "shot", "shoulder", "show", "sibling", "sickness",
     "side", "sign", "signal", "signature", "significance", "silence", "silhouette", "silver", "similarity", "simple", "single", "sip", "site",
     "situation", "size", "skill", "skin", "skirt", "sky", "sleep", "slice", "slide", "slope", "smile", "snake", "snow", "snowflake", "society",
     "software", "soil", "solarium", "solution", "source", "space", "speaker", "species", "specification", "speech", "speed", "spend", "spin",
     "spirit", "sponge", "sport", "spot", "spread", "spring", "square", "stability", "staff", "stage", "stand", "standard", "star", "start",
     "state", "statement", "status", "step", "stick", "still", "stock", "stone", "stop", "store", "story", "strategy", "strawberry", "street",
     "strength", "structure", "student", "studio", "study", "stuff", "style", "subject", "success", "succulent", "sugar", "suggestion", "suit",
     "summer", "sun", "supermarket", "supper", "supply", "support", "surface", "surprise", "survey", "susan", "swamp", "system", "table",
     "tadpole", "tale", "talk", "tape", "tarantula", "target", "task", "taste", "tax", "teacher", "team", "technology", "television", "tell",
     "temperature", "tendency", "tent", "term", "test", "text", "that", "their", "theirs", "them", "theme", "theory", "thermos", "thesis", "they",
     "thing", "thought", "threat", "thunder", "ticket", "tiger", "time", "timing", "tip", "tissue", "title", "toad", "tomato", "tool", "top",
     "topic", "tornado", "total", "touch", "tour", "tournament", "town", "track", "trade", "tradition", "traffic", "trail", "train",
     "transaction", "transition", "transport", "travel", "treat", "treatment", "tree", "trial", "triangle", "trip", "trouble", "truck", "trust",
     "truth", "try", "tuba", "tube", "tulip", "tuna", "tune", "tunnel", "turkey", "turn", "turtle", "twine", "type", "ukulele", "umbrella",
     "unicorn", "unicycle", "unit", "universe", "university", "update", "upgrade", "uranium", "urchin", "us", "user", "utensil", "utility",
     "vacuum", "valley", "value", "vampire", "van", "vanilla", "variety", "vegetable", "vehicle", "velociraptor", "version", "vertex", "video",
     "view", "village", "vine", "viola", "violation", "violin", "virtue", "vision", "visit", "visual", "voice", "volcano", "volleyball", "volume",
     "vortex", "vote", "waffle", "wage", "wait", "walk", "wall", "walrus", "war", "watch", "water", "waterfall", "watermelon", "wave", "way",
     "we", "wealth", "weapon", "wear", "weather", "web", "wedding", "weed", "week", "weight", "welcome", "welfare", "well", "west", "whale",
     "wheat", "wheel", "which", "while", "white", "who", "whole", "whom", "whose", "windmill", "window", "wolf", "wolverine", "wombat", "wrench",
     "x-ray", "xenon", "xenophobe", "xerox", "xylophone", "xylophonist", "yacht", "yak", "yam", "yarn", "yawn", "yearbook", "yellow", "yeti",
     "yo-yo", "yoga", "yogurt", "you", "your", "yours", "zeal", "zealot", "zebra", "zephyr", "zeppelin", "zipper", "zodiac", "zombie",
     "zucchini"
     ]
