verb = [
     "accept", "achieve", "add", "admire", "admit", "advance", "advise", "afford", "agree", "alert", "allow", "amplify", "amuse", "analyze",
     "announce", "annoy", "answer", "apologize", "appear", "append", "applaud", "apply", "appreciate", "approve", "argue", "arrange", "arrest",
     "arrive", "ask", "assemble", "assign", "assist", "assume", "assure", "attach", "attack", "attempt", "attend", "attract", "audit", "avoid",
     "bake", "balance", "ban", "bang", "bare", "bat", "bathe", "battle", "beam", "bear", "beat", "become", "beg", "begin", "behave", "believe",
     "belong", "bend", "bet", "bid", "bind", "bite", "bleach", "bleed", "bless", "blind", "blink", "blot", "blow", "blush", "boast", "boil",
     "bolt", "bomb", "book", "bore", "borrow", "bounce", "bow", "box", "brake", "branch", "break", "breathe", "bring", "bruise", "brush",
     "bubble", "build", "bump", "burn", "bury", "buzz", "calculate", "call", "camp", "care", "carry", "carve", "catch", "cause", "celebrate",
     "challenge", "change", "charge", "chase", "cheat", "check", "cheer", "chew", "choke", "choose", "chop", "claim", "clap", "clean", "clear",
     "clip", "close", "coach", "coil", "collect", "color", "comb", "come", "command", "communicate", "compare", "compete", "complain", "complete",
     "complicate", "compute", "conceal", "concentrate", "concern", "confess", "confuse", "connect", "consider", "consist", "contain", "continue",
     "contrast", "copy", "correct", "cough", "count", "cover", "crack", "crash", "crawl", "create", "criticize", "cross", "crush", "cry", "cure",
     "curl", "curve", "cut", "cycle", "dam", "damage", "dance", "dare", "decay", "deceive", "decide", "decline", "decorate", "decrease", "defend",
     "defile", "delay", "delight", "deliver", "demand", "deny", "depart", "depend", "describe", "desert", "deserve", "destroy", "detect",
     "determine", "develop", "dirty", "disable", "disagree", "disappear", "disapprove", "disarm", "discourage", "discover", "discuss", "dislike",
     "divide", "do", "doubt", "drag", "drain", "draw", "dream", "dress", "drink", "drip", "drop", "drown", "drum", "dry", "dust", "earn", "eat",
     "educate", "elevate", "embarrass", "employ", "empty", "enable", "encourage", "end", "enjoy", "enter", "entertain", "escape", "estimate",
     "examine", "excite", "exclude", "excuse", "exercise", "exist", "expand", "expect", "explain", "explode", "express", "extend", "face", "fade",
     "fail", "fancy", "fasten", "fax", "fear", "feed", "feel", "fence", "fetch", "fight", "file", "fill", "film", "find", "fine", "finish",
     "fire", "fit", "fix", "flap", "flash", "float", "flood", "flow", "flower", "fly", "fold", "follow", "fool", "force", "forget", "form",
     "foster", "found", "frame", "frighten", "frolic", "frown", "fry", "gain", "gather", "gaze", "generate", "get", "give", "go", "grip", "groan",
     "grow", "guarantee", "guard", "guess", "guide", "halt", "hammer", "hand", "handle", "hang", "happen", "harass", "harm", "hate", "haunt",
     "have", "head", "heal", "heap", "hear", "heat", "help", "hold", "hook", "hop", "hope", "hover", "hug", "hum", "hunt", "hurry", "identify",
     "ignore", "illustrate", "imagine", "impress", "improve", "include", "increase", "influence", "inform", "inject", "injure", "instruct",
     "intend", "interest", "interfere", "interrupt", "introduce", "invent", "invite", "irritate", "itch", "jail", "jam", "jiggle", "jog", "join",
     "joke", "judge", "juggle", "juice", "jump", "keep", "kick", "kill", "kiss", "kneel", "knit", "knock", "knot", "know", "label", "land",
     "last", "laugh", "launch", "lead", "learn", "leave", "let", "level", "license", "lick", "lie", "lift", "light", "lighten", "like", "list",
     "listen", "live", "load", "lock", "long", "look", "lose", "love", "lower", "mail", "make", "manage", "map", "mar", "march", "mark", "marry",
     "mash", "match", "mate", "matter", "maul", "measure", "meet", "melt", "memorize", "mend", "mess up", "milk", "mine", "miss", "mix", "moan",
     "modify", "modulate", "mope", "mourn", "move", "muddle", "mug", "multiply", "murder", "nail", "name", "need", "neglect", "nibble", "nip",
     "nod", "note", "notice", "number", "obey", "object", "observe", "obtain", "occur", "offend", "offer", "open", "order", "overflow", "owe",
     "own", "pack", "paddle", "paint", "park", "part", "pass", "paste", "pat", "pause", "peck", "pedal", "peel", "peep", "perform", "permit",
     "phone", "pick", "pinch", "pine", "place", "plan", "plant", "play", "please", "plug", "point", "poke", "polish", "pop", "possess", "post",
     "pour", "practice", "praise", "pray", "preach", "precede", "predict", "prefer", "prepare", "present", "preserve", "press", "pretend",
     "prevent", "prick", "print", "proceed", "produce", "program", "promise", "pronounce", "protect", "provide", "pull", "pump", "punch",
     "punish", "purchase", "push", "put", "question", "queue", "quote", "race", "radiate", "rain", "raise", "reach", "read", "realize", "receive",
     "recite", "recognize", "record", "reduce", "reflect", "refuse", "regret", "reign", "reject", "rejoice", "relax", "release", "rely", "remain",
     "remember", "remind", "remove", "repair", "repeat", "replace", "reply", "report", "reproduce", "request", "rescue", "resist", "retire",
     "retreat", "return", "reveal", "reward", "rhyme", "rinse", "risk", "rob", "rock", "roll", "rot", "rub", "ruin", "rule", "run", "rush",
     "sack", "sail", "salivate", "salvage", "satisfy", "save", "saw", "scare", "scatter", "scold", "scorch", "scrape", "scratch", "scream",
     "screw", "scribble", "scrub", "seal", "search", "secrete", "see", "seem", "segment", "sell", "separate", "sequence", "serve", "settle",
     "shade", "shake", "shave", "shelter", "shiver", "shock", "shop", "shout", "show", "shrink", "shrug", "sigh", "sign", "signal", "simplify",
     "sin", "sing", "sip", "ski", "skip", "slap", "slip", "slow", "smash", "smell", "smile", "smoke", "snatch", "sneeze", "sniff", "snore",
     "snow", "soak", "soothe", "sound", "spare", "spark", "sparkle", "speak", "spell", "spill", "spoil", "spot", "spray", "sprout", "squash",
     "squeak", "squeal", "squeeze", "stain", "stamp", "stare", "start", "state", "stay", "steer", "step", "stir", "stitch", "stop", "store",
     "strap", "strengthen", "stretch", "strip", "stroke", "stuff", "submit", "subtract", "succeed", "suck", "suffer", "suggest", "suit", "supply",
     "support", "suppose", "surprise", "surround", "suspect", "suspend", "swim", "switch", "take", "talk", "tame", "tap", "tarnish", "taste",
     "teach", "tease", "telephone", "tell", "tempt", "tend", "terrify", "test", "thank", "thaw", "theorize", "think", "thrash", "throttle",
     "throw", "tick", "tickle", "tie", "time", "tip", "tire", "touch", "tour", "tow", "trace", "trade", "train", "transport", "trap", "travel",
     "treat", "tremble", "trick", "try", "tuck", "tune", "turn", "tweak", "understand", "use", "value", "walk", "want", "waste", "watch", "wean",
     "weep", "weigh", "went", "whisper", "win", "wish", "withdraw", "work", "worsen", "write"
     ]